### ISSUE TITLE
Got crash when the JSON input is invalid

### ISSUE THREAD

**Issue by kinfkong** [izniburak/appstore-notifications-go#4]
andleKatagoUsages" file="/Users/jinggangwang/gochess/ikatago-service/usage/service.go:397"
Sep 10 11:45:26 iZ7xva13ausve1mn11cdsgZ ikatago-service[2421962]: 2024/09/10 11:45:26 http: panic serving 127.0.0.1:43234: unexpected end of JSON input
Sep 10 11:45:26 iZ7xva13ausve1mn11cdsgZ ikatago-service[2421962]: goroutine 3551070 [running]:
Sep 10 11:45:26 iZ7xva13ausve1mn11cdsgZ ikatago-service[2421962]: net/http.(*conn).serve.func1()
Sep 10 11:45:26 iZ7xva13ausve1mn11cdsgZ ikatago-service[2421962]:         /usr/local/go/src/net/http/server.go:1868 +0xb9
Sep 10 11:45:26 iZ7xva13ausve1mn11cdsgZ ikatago-service[2421962]: panic({0xcfd8e0?, 0xc00171c780?})
Sep 10 11:45:26 iZ7xva13ausve1mn11cdsgZ ikatago-service[2421962]:         /usr/local/go/src/runtime/panic.go:920 +0x270
Sep 10 11:45:26 iZ7xva13ausve1mn11cdsgZ ikatago-service[2421962]: github.com/izniburak/appstore-notifications-go.(*AppStoreServerNotification).parseJwtSignedPayload(0xc00178d5d0, {0x0, 0x0})
Sep 10 11:45:26 iZ7xva13ausve1mn11cdsgZ ikatago-service[2421962]:         /Users/jinggangwang/go/pkg/mod/github.com/izniburak/appstore-notifications-go@v1.2.0/v2.go:111 +0x43d
Sep 10 11:45:26 iZ7xva13ausve1mn11cdsgZ ikatago-service[2421962]: github.com/izniburak/appstore-notifications-go.New(...)
Sep 10 11:45:26 iZ7xva13ausve1mn11cdsgZ ikatago-service[2421962]:         /Users/jinggangwang/go/pkg/mod/github.com/izniburak/appstore-notifications-go@v1.2.0/v2.go:19

**Comment by izniburak** [comment]
@kinfkong 
App Store Connect API might be changed and added/removed some new params. I'll check it and if I find any issue, I'll release a new version of the package.

Also, your data/params are correct, right? Did you check it the params?

**Comment by AnyCPU** [comment]
Hi @kinfkong, it looks as if it is already fixed on main.

Hi @izniburak,
This one is fixed on main by #6 (coincidence :smiley:).

But the fix isn't in any released tag yet. 
The v1.3.0/latest points to an "old release".

Could you cut a new release off main?

A possible changelog entry might look like:

## [2.0.0] - 2026-05-12

### Changed
- **BREAKING:** `New(payload, appleRootCert)` now returns `(*AppStoreServerNotification, error)` instead of `*AppStoreServerNotification`. Parse failures surface as errors instead of panics;
- **BREAKING:** Upgraded `github.com/golang-jwt/jwt` to `jwt/v5`. Embedders of `NotificationPayload`, `TransactionInfo`, or `RenewalInfo` must update their import path;
- `TransactionInfo` and `RenewalInfo` are now `nil` when the notification carries no inner signed JWT (`TEST`, `EXTERNAL_PURCHASE_TOKEN`, `RENEWAL_EXTENDED`). Callers must nil-check before dereferencing;
- `IsValid` is set only after the full pipeline - including any inner JWTs - completes successfully.

### Fixed
- `New` no longer panics on malformed input. Empty strings, non-JWT garbage, fewer than three JWS segments, and missing or short `x5c` chains now return descriptive errors (#4);
- Notifications without inner signed JWTs (`TEST`, `EXTERNAL_PURCHASE_TOKEN`, `RENEWAL_EXTENDED`) no longer fail parsing.
  
### Added
- `TestMalformedPayloads` regression test pinning the no-panic contract across four malformed inputs;
- CI now runs on Go 1.21.

**Comment by izniburak** [comment]
I've just released v2.0.0. Thanks for the contributions!
